addons:
  sonarcloud:
    organization: "cnessonarreportupdatedscalian"
    token: "d51d9f18fc461a4df3f5e2f43f0a94fac8df7844"
      

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=bowserax_TestSonarAnalysis